version: '3.8'

services:
  postgres-dw:
    image: postgres:15-alpine
    container_name: sales_dw_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sales_dw_local
    ports:
      - "5433:5432"
    volumes:
      - ./dw:/docker-entrypoint-initdb.d
      - postgres_dw_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_dw_data:
